services:
  backend:
    build: ./mapbackend
    entrypoint: /src/backend/entrypoint.prod.sh
    volumes:
      - ./mapbackend:/src/backend/
      - static_volume:/src/backend/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_DEBUG=0
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 2s
      timeout: 5s
      retries: 5
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - static_volume:/src/backend/staticfiles

volumes:
  postgres_data:
  static_volume:
