services:
  backend:
    build: ./mapbackend
    command: gunicorn mapbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./mapbackend:/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
