version: '3.8'

services:
  backend:
    build: ./mapbackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mapbackend:/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data: