# Generated by Django 4.2.6 on 2023-10-11 19:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("label_text", models.CharField(max_length=255)),
                (
                    "position",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(24.9384, 60.1699),
                        geography=True,
                        srid=4326,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
