# Generated by Django 4.2.6 on 2023-10-11 19:50

from django.db import migrations
import os
from sys import path
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))

def load_fixtures(apps, schema_editor):
    call_command("loaddata", os.path.join(fixture_dir, "initial_data.json"))
    pass
    
class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('points', '0002_userpoint_user'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, migrations.RunPython.noop)
    ]
